// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: App.proto

package com.clickstream.app.proto;

public interface AppOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clickstream.proto.App)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Version of the client app. Use this property to send version with every event.
   * This allows for segmentation based on the app version.
   * Sample values: "1.0.0", "1.0.1".
   * </pre>
   *
   * <code>string version = 1;</code>
   * @return The version.
   */
  String getVersion();
  /**
   * <pre>
   * Version of the client app. Use this property to send version with every event.
   * This allows for segmentation based on the app version.
   * Sample values: "1.0.0", "1.0.1".
   * </pre>
   *
   * <code>string version = 1;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <pre>
   * Package name of the client app. Use this property to send package name with every event.
   * Sample values: "com.clickstream.app".
   * </pre>
   *
   * <code>string package_name = 2;</code>
   * @return The packageName.
   */
  String getPackageName();
  /**
   * <pre>
   * Package name of the client app. Use this property to send package name with every event.
   * Sample values: "com.clickstream.app".
   * </pre>
   *
   * <code>string package_name = 2;</code>
   * @return The bytes for packageName.
   */
  com.google.protobuf.ByteString
      getPackageNameBytes();
}
