// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.clickstream.app.proto;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
