// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: App.proto

package clickstream.proto;

public final class AppProto {
  private AppProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
