// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Device.proto

package clickstream.proto;

/**
 * <pre>
 * Corresponds to the device being used by the customer. Holds the respective details for the device under use.
 * </pre>
 *
 * Protobuf type {@code clickstream.proto.Device}
 */
public  final class Device extends
    com.google.protobuf.GeneratedMessageLite<
        Device, Device.Builder> implements
    // @@protoc_insertion_point(message_implements:clickstream.proto.Device)
    DeviceOrBuilder {
  private Device() {
    operatingSystem_ = "";
    operatingSystemVersion_ = "";
    deviceMake_ = "";
    deviceModel_ = "";
  }
  public static final int OPERATING_SYSTEM_FIELD_NUMBER = 1;
  private String operatingSystem_;
  /**
   * <pre>
   * Operating system of the device.
   * Sample values: "iOS", "Android".
   * </pre>
   *
   * <code>string operating_system = 1;</code>
   * @return The operatingSystem.
   */
  @Override
  public String getOperatingSystem() {
    return operatingSystem_;
  }
  /**
   * <pre>
   * Operating system of the device.
   * Sample values: "iOS", "Android".
   * </pre>
   *
   * <code>string operating_system = 1;</code>
   * @return The bytes for operatingSystem.
   */
  @Override
  public com.google.protobuf.ByteString
      getOperatingSystemBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(operatingSystem_);
  }
  /**
   * <pre>
   * Operating system of the device.
   * Sample values: "iOS", "Android".
   * </pre>
   *
   * <code>string operating_system = 1;</code>
   * @param value The operatingSystem to set.
   */
  private void setOperatingSystem(
      String value) {
    Class<?> valueClass = value.getClass();
  
    operatingSystem_ = value;
  }
  /**
   * <pre>
   * Operating system of the device.
   * Sample values: "iOS", "Android".
   * </pre>
   *
   * <code>string operating_system = 1;</code>
   */
  private void clearOperatingSystem() {
    
    operatingSystem_ = getDefaultInstance().getOperatingSystem();
  }
  /**
   * <pre>
   * Operating system of the device.
   * Sample values: "iOS", "Android".
   * </pre>
   *
   * <code>string operating_system = 1;</code>
   * @param value The bytes for operatingSystem to set.
   */
  private void setOperatingSystemBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    operatingSystem_ = value.toStringUtf8();
    
  }

  public static final int OPERATING_SYSTEM_VERSION_FIELD_NUMBER = 2;
  private String operatingSystemVersion_;
  /**
   * <pre>
   * Version of the Operating system.
   * Sample values: "29", "15.1".
   * </pre>
   *
   * <code>string operating_system_version = 2;</code>
   * @return The operatingSystemVersion.
   */
  @Override
  public String getOperatingSystemVersion() {
    return operatingSystemVersion_;
  }
  /**
   * <pre>
   * Version of the Operating system.
   * Sample values: "29", "15.1".
   * </pre>
   *
   * <code>string operating_system_version = 2;</code>
   * @return The bytes for operatingSystemVersion.
   */
  @Override
  public com.google.protobuf.ByteString
      getOperatingSystemVersionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(operatingSystemVersion_);
  }
  /**
   * <pre>
   * Version of the Operating system.
   * Sample values: "29", "15.1".
   * </pre>
   *
   * <code>string operating_system_version = 2;</code>
   * @param value The operatingSystemVersion to set.
   */
  private void setOperatingSystemVersion(
      String value) {
    Class<?> valueClass = value.getClass();
  
    operatingSystemVersion_ = value;
  }
  /**
   * <pre>
   * Version of the Operating system.
   * Sample values: "29", "15.1".
   * </pre>
   *
   * <code>string operating_system_version = 2;</code>
   */
  private void clearOperatingSystemVersion() {
    
    operatingSystemVersion_ = getDefaultInstance().getOperatingSystemVersion();
  }
  /**
   * <pre>
   * Version of the Operating system.
   * Sample values: "29", "15.1".
   * </pre>
   *
   * <code>string operating_system_version = 2;</code>
   * @param value The bytes for operatingSystemVersion to set.
   */
  private void setOperatingSystemVersionBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    operatingSystemVersion_ = value.toStringUtf8();
    
  }

  public static final int DEVICE_MAKE_FIELD_NUMBER = 3;
  private String deviceMake_;
  /**
   * <pre>
   * Device manufacturer name.
   * Sample values: "Samsung", "HMD Global", "Apple"
   * </pre>
   *
   * <code>string device_make = 3;</code>
   * @return The deviceMake.
   */
  @Override
  public String getDeviceMake() {
    return deviceMake_;
  }
  /**
   * <pre>
   * Device manufacturer name.
   * Sample values: "Samsung", "HMD Global", "Apple"
   * </pre>
   *
   * <code>string device_make = 3;</code>
   * @return The bytes for deviceMake.
   */
  @Override
  public com.google.protobuf.ByteString
      getDeviceMakeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(deviceMake_);
  }
  /**
   * <pre>
   * Device manufacturer name.
   * Sample values: "Samsung", "HMD Global", "Apple"
   * </pre>
   *
   * <code>string device_make = 3;</code>
   * @param value The deviceMake to set.
   */
  private void setDeviceMake(
      String value) {
    Class<?> valueClass = value.getClass();
  
    deviceMake_ = value;
  }
  /**
   * <pre>
   * Device manufacturer name.
   * Sample values: "Samsung", "HMD Global", "Apple"
   * </pre>
   *
   * <code>string device_make = 3;</code>
   */
  private void clearDeviceMake() {
    
    deviceMake_ = getDefaultInstance().getDeviceMake();
  }
  /**
   * <pre>
   * Device manufacturer name.
   * Sample values: "Samsung", "HMD Global", "Apple"
   * </pre>
   *
   * <code>string device_make = 3;</code>
   * @param value The bytes for deviceMake to set.
   */
  private void setDeviceMakeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    deviceMake_ = value.toStringUtf8();
    
  }

  public static final int DEVICE_MODEL_FIELD_NUMBER = 4;
  private String deviceModel_;
  /**
   * <pre>
   * Device model information.
   * Sample values: "iPhone 11", "Samsung M90".
   * </pre>
   *
   * <code>string device_model = 4;</code>
   * @return The deviceModel.
   */
  @Override
  public String getDeviceModel() {
    return deviceModel_;
  }
  /**
   * <pre>
   * Device model information.
   * Sample values: "iPhone 11", "Samsung M90".
   * </pre>
   *
   * <code>string device_model = 4;</code>
   * @return The bytes for deviceModel.
   */
  @Override
  public com.google.protobuf.ByteString
      getDeviceModelBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(deviceModel_);
  }
  /**
   * <pre>
   * Device model information.
   * Sample values: "iPhone 11", "Samsung M90".
   * </pre>
   *
   * <code>string device_model = 4;</code>
   * @param value The deviceModel to set.
   */
  private void setDeviceModel(
      String value) {
    Class<?> valueClass = value.getClass();
  
    deviceModel_ = value;
  }
  /**
   * <pre>
   * Device model information.
   * Sample values: "iPhone 11", "Samsung M90".
   * </pre>
   *
   * <code>string device_model = 4;</code>
   */
  private void clearDeviceModel() {
    
    deviceModel_ = getDefaultInstance().getDeviceModel();
  }
  /**
   * <pre>
   * Device model information.
   * Sample values: "iPhone 11", "Samsung M90".
   * </pre>
   *
   * <code>string device_model = 4;</code>
   * @param value The bytes for deviceModel to set.
   */
  private void setDeviceModelBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    deviceModel_ = value.toStringUtf8();
    
  }

  public static Device parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static Device parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static Device parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static Device parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static Device parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static Device parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static Device parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static Device parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static Device parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static Device parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static Device parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static Device parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(Device prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Corresponds to the device being used by the customer. Holds the respective details for the device under use.
   * </pre>
   *
   * Protobuf type {@code clickstream.proto.Device}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        Device, Builder> implements
      // @@protoc_insertion_point(builder_implements:clickstream.proto.Device)
      DeviceOrBuilder {
    // Construct using com.clickstream.app.proto.Device.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Operating system of the device.
     * Sample values: "iOS", "Android".
     * </pre>
     *
     * <code>string operating_system = 1;</code>
     * @return The operatingSystem.
     */
    @Override
    public String getOperatingSystem() {
      return instance.getOperatingSystem();
    }
    /**
     * <pre>
     * Operating system of the device.
     * Sample values: "iOS", "Android".
     * </pre>
     *
     * <code>string operating_system = 1;</code>
     * @return The bytes for operatingSystem.
     */
    @Override
    public com.google.protobuf.ByteString
        getOperatingSystemBytes() {
      return instance.getOperatingSystemBytes();
    }
    /**
     * <pre>
     * Operating system of the device.
     * Sample values: "iOS", "Android".
     * </pre>
     *
     * <code>string operating_system = 1;</code>
     * @param value The operatingSystem to set.
     * @return This builder for chaining.
     */
    public Builder setOperatingSystem(
        String value) {
      copyOnWrite();
      instance.setOperatingSystem(value);
      return this;
    }
    /**
     * <pre>
     * Operating system of the device.
     * Sample values: "iOS", "Android".
     * </pre>
     *
     * <code>string operating_system = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOperatingSystem() {
      copyOnWrite();
      instance.clearOperatingSystem();
      return this;
    }
    /**
     * <pre>
     * Operating system of the device.
     * Sample values: "iOS", "Android".
     * </pre>
     *
     * <code>string operating_system = 1;</code>
     * @param value The bytes for operatingSystem to set.
     * @return This builder for chaining.
     */
    public Builder setOperatingSystemBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setOperatingSystemBytes(value);
      return this;
    }

    /**
     * <pre>
     * Version of the Operating system.
     * Sample values: "29", "15.1".
     * </pre>
     *
     * <code>string operating_system_version = 2;</code>
     * @return The operatingSystemVersion.
     */
    @Override
    public String getOperatingSystemVersion() {
      return instance.getOperatingSystemVersion();
    }
    /**
     * <pre>
     * Version of the Operating system.
     * Sample values: "29", "15.1".
     * </pre>
     *
     * <code>string operating_system_version = 2;</code>
     * @return The bytes for operatingSystemVersion.
     */
    @Override
    public com.google.protobuf.ByteString
        getOperatingSystemVersionBytes() {
      return instance.getOperatingSystemVersionBytes();
    }
    /**
     * <pre>
     * Version of the Operating system.
     * Sample values: "29", "15.1".
     * </pre>
     *
     * <code>string operating_system_version = 2;</code>
     * @param value The operatingSystemVersion to set.
     * @return This builder for chaining.
     */
    public Builder setOperatingSystemVersion(
        String value) {
      copyOnWrite();
      instance.setOperatingSystemVersion(value);
      return this;
    }
    /**
     * <pre>
     * Version of the Operating system.
     * Sample values: "29", "15.1".
     * </pre>
     *
     * <code>string operating_system_version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOperatingSystemVersion() {
      copyOnWrite();
      instance.clearOperatingSystemVersion();
      return this;
    }
    /**
     * <pre>
     * Version of the Operating system.
     * Sample values: "29", "15.1".
     * </pre>
     *
     * <code>string operating_system_version = 2;</code>
     * @param value The bytes for operatingSystemVersion to set.
     * @return This builder for chaining.
     */
    public Builder setOperatingSystemVersionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setOperatingSystemVersionBytes(value);
      return this;
    }

    /**
     * <pre>
     * Device manufacturer name.
     * Sample values: "Samsung", "HMD Global", "Apple"
     * </pre>
     *
     * <code>string device_make = 3;</code>
     * @return The deviceMake.
     */
    @Override
    public String getDeviceMake() {
      return instance.getDeviceMake();
    }
    /**
     * <pre>
     * Device manufacturer name.
     * Sample values: "Samsung", "HMD Global", "Apple"
     * </pre>
     *
     * <code>string device_make = 3;</code>
     * @return The bytes for deviceMake.
     */
    @Override
    public com.google.protobuf.ByteString
        getDeviceMakeBytes() {
      return instance.getDeviceMakeBytes();
    }
    /**
     * <pre>
     * Device manufacturer name.
     * Sample values: "Samsung", "HMD Global", "Apple"
     * </pre>
     *
     * <code>string device_make = 3;</code>
     * @param value The deviceMake to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceMake(
        String value) {
      copyOnWrite();
      instance.setDeviceMake(value);
      return this;
    }
    /**
     * <pre>
     * Device manufacturer name.
     * Sample values: "Samsung", "HMD Global", "Apple"
     * </pre>
     *
     * <code>string device_make = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceMake() {
      copyOnWrite();
      instance.clearDeviceMake();
      return this;
    }
    /**
     * <pre>
     * Device manufacturer name.
     * Sample values: "Samsung", "HMD Global", "Apple"
     * </pre>
     *
     * <code>string device_make = 3;</code>
     * @param value The bytes for deviceMake to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceMakeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDeviceMakeBytes(value);
      return this;
    }

    /**
     * <pre>
     * Device model information.
     * Sample values: "iPhone 11", "Samsung M90".
     * </pre>
     *
     * <code>string device_model = 4;</code>
     * @return The deviceModel.
     */
    @Override
    public String getDeviceModel() {
      return instance.getDeviceModel();
    }
    /**
     * <pre>
     * Device model information.
     * Sample values: "iPhone 11", "Samsung M90".
     * </pre>
     *
     * <code>string device_model = 4;</code>
     * @return The bytes for deviceModel.
     */
    @Override
    public com.google.protobuf.ByteString
        getDeviceModelBytes() {
      return instance.getDeviceModelBytes();
    }
    /**
     * <pre>
     * Device model information.
     * Sample values: "iPhone 11", "Samsung M90".
     * </pre>
     *
     * <code>string device_model = 4;</code>
     * @param value The deviceModel to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceModel(
        String value) {
      copyOnWrite();
      instance.setDeviceModel(value);
      return this;
    }
    /**
     * <pre>
     * Device model information.
     * Sample values: "iPhone 11", "Samsung M90".
     * </pre>
     *
     * <code>string device_model = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceModel() {
      copyOnWrite();
      instance.clearDeviceModel();
      return this;
    }
    /**
     * <pre>
     * Device model information.
     * Sample values: "iPhone 11", "Samsung M90".
     * </pre>
     *
     * <code>string device_model = 4;</code>
     * @param value The bytes for deviceModel to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceModelBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDeviceModelBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:clickstream.proto.Device)
  }
  @Override
  @SuppressWarnings({"unchecked", "fallthrough"})
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new Device();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          Object[] objects = new Object[] {
            "operatingSystem_",
            "operatingSystemVersion_",
            "deviceMake_",
            "deviceModel_",
          };
          String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<Device> parser = PARSER;
        if (parser == null) {
          synchronized (Device.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<Device>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:clickstream.proto.Device)
  private static final Device DEFAULT_INSTANCE;
  static {
    Device defaultInstance = new Device();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Device.class, defaultInstance);
  }

  public static Device getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Device> PARSER;

  public static com.google.protobuf.Parser<Device> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

