// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Device.proto

package clickstream.proto;

public interface DeviceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clickstream.proto.Device)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Operating system of the device.
   * Sample values: "iOS", "Android".
   * </pre>
   *
   * <code>string operating_system = 1;</code>
   * @return The operatingSystem.
   */
  String getOperatingSystem();
  /**
   * <pre>
   * Operating system of the device.
   * Sample values: "iOS", "Android".
   * </pre>
   *
   * <code>string operating_system = 1;</code>
   * @return The bytes for operatingSystem.
   */
  com.google.protobuf.ByteString
      getOperatingSystemBytes();

  /**
   * <pre>
   * Version of the Operating system.
   * Sample values: "29", "15.1".
   * </pre>
   *
   * <code>string operating_system_version = 2;</code>
   * @return The operatingSystemVersion.
   */
  String getOperatingSystemVersion();
  /**
   * <pre>
   * Version of the Operating system.
   * Sample values: "29", "15.1".
   * </pre>
   *
   * <code>string operating_system_version = 2;</code>
   * @return The bytes for operatingSystemVersion.
   */
  com.google.protobuf.ByteString
      getOperatingSystemVersionBytes();

  /**
   * <pre>
   * Device manufacturer name.
   * Sample values: "Samsung", "HMD Global", "Apple"
   * </pre>
   *
   * <code>string device_make = 3;</code>
   * @return The deviceMake.
   */
  String getDeviceMake();
  /**
   * <pre>
   * Device manufacturer name.
   * Sample values: "Samsung", "HMD Global", "Apple"
   * </pre>
   *
   * <code>string device_make = 3;</code>
   * @return The bytes for deviceMake.
   */
  com.google.protobuf.ByteString
      getDeviceMakeBytes();

  /**
   * <pre>
   * Device model information.
   * Sample values: "iPhone 11", "Samsung M90".
   * </pre>
   *
   * <code>string device_model = 4;</code>
   * @return The deviceModel.
   */
  String getDeviceModel();
  /**
   * <pre>
   * Device model information.
   * Sample values: "iPhone 11", "Samsung M90".
   * </pre>
   *
   * <code>string device_model = 4;</code>
   * @return The bytes for deviceModel.
   */
  com.google.protobuf.ByteString
      getDeviceModelBytes();
}
