// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Device.proto

package clickstream.proto;

public final class DeviceProto {
  private DeviceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
