// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raccoon.proto

package clickstream.internal.networklayer.proto.raccoon;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:raystack.raccoon.v1beta1.Event)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   *`event_bytes` is where you put bytes serialized event.
   * </pre>
   *
   * <code>bytes event_bytes = 1;</code>
   * @return The eventBytes.
   */
  com.google.protobuf.ByteString getEventBytes();

  /**
   * <pre>
   *`type` denotes an event type that the producer of this proto message may set.
   *It is currently used by raccoon to distribute events to respective Kafka topics. However the
   *users of this proto can use this type to set strings which can be processed in their
   *ingestion systems to distribute or perform other functions.
   * </pre>
   *
   * <code>string type = 2;</code>
   * @return The type.
   */
  String getType();
  /**
   * <pre>
   *`type` denotes an event type that the producer of this proto message may set.
   *It is currently used by raccoon to distribute events to respective Kafka topics. However the
   *users of this proto can use this type to set strings which can be processed in their
   *ingestion systems to distribute or perform other functions.
   * </pre>
   *
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
