// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raccoon.proto

package clickstream.internal.networklayer.proto.raccoon;

/**
 * Protobuf enum {@code raystack.raccoon.v1beta1.Status}
 */
public enum Status
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>STATUS_UNSPECIFIED = 0;</code>
   */
  STATUS_UNSPECIFIED(0),
  /**
   * <code>STATUS_SUCCESS = 1;</code>
   */
  STATUS_SUCCESS(1),
  /**
   * <code>STATUS_ERROR = 2;</code>
   */
  STATUS_ERROR(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>STATUS_UNSPECIFIED = 0;</code>
   */
  public static final int STATUS_UNSPECIFIED_VALUE = 0;
  /**
   * <code>STATUS_SUCCESS = 1;</code>
   */
  public static final int STATUS_SUCCESS_VALUE = 1;
  /**
   * <code>STATUS_ERROR = 2;</code>
   */
  public static final int STATUS_ERROR_VALUE = 2;


  @Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static Status valueOf(int value) {
    return forNumber(value);
  }

  public static Status forNumber(int value) {
    switch (value) {
      case 0: return STATUS_UNSPECIFIED;
      case 1: return STATUS_SUCCESS;
      case 2: return STATUS_ERROR;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Status>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Status> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Status>() {
          @Override
          public Status findValueByNumber(int number) {
            return Status.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return StatusVerifier.INSTANCE;
  }

  private static final class StatusVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new StatusVerifier();
          @Override
          public boolean isInRange(int number) {
            return Status.forNumber(number) != null;
          }
        };

  private final int value;

  private Status(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:raystack.raccoon.v1beta1.Status)
}

