// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Health.proto

package clickstream.health.proto;

/**
 * Protobuf type {@code clickstream.health.proto.HealthDetails}
 */
public  final class HealthDetails extends
    com.google.protobuf.GeneratedMessageLite<
        HealthDetails, HealthDetails.Builder> implements
    // @@protoc_insertion_point(message_implements:clickstream.health.proto.HealthDetails)
    HealthDetailsOrBuilder {
  private HealthDetails() {
    eventGuids_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    eventBatchGuids_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  public static final int EVENT_GUIDS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<String> eventGuids_;
  /**
   * <pre>
   * Array of event guids.
   * </pre>
   *
   * <code>repeated string event_guids = 1;</code>
   * @return A list containing the eventGuids.
   */
  @Override
  public java.util.List<String> getEventGuidsList() {
    return eventGuids_;
  }
  /**
   * <pre>
   * Array of event guids.
   * </pre>
   *
   * <code>repeated string event_guids = 1;</code>
   * @return The count of eventGuids.
   */
  @Override
  public int getEventGuidsCount() {
    return eventGuids_.size();
  }
  /**
   * <pre>
   * Array of event guids.
   * </pre>
   *
   * <code>repeated string event_guids = 1;</code>
   * @param index The index of the element to return.
   * @return The eventGuids at the given index.
   */
  @Override
  public String getEventGuids(int index) {
    return eventGuids_.get(index);
  }
  /**
   * <pre>
   * Array of event guids.
   * </pre>
   *
   * <code>repeated string event_guids = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the eventGuids at the given index.
   */
  @Override
  public com.google.protobuf.ByteString
      getEventGuidsBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        eventGuids_.get(index));
  }
  private void ensureEventGuidsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<String> tmp =
        eventGuids_;  if (!tmp.isModifiable()) {
      eventGuids_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <pre>
   * Array of event guids.
   * </pre>
   *
   * <code>repeated string event_guids = 1;</code>
   * @param index The index to set the value at.
   * @param value The eventGuids to set.
   */
  private void setEventGuids(
      int index, String value) {
    Class<?> valueClass = value.getClass();
  ensureEventGuidsIsMutable();
    eventGuids_.set(index, value);
  }
  /**
   * <pre>
   * Array of event guids.
   * </pre>
   *
   * <code>repeated string event_guids = 1;</code>
   * @param value The eventGuids to add.
   */
  private void addEventGuids(
      String value) {
    Class<?> valueClass = value.getClass();
  ensureEventGuidsIsMutable();
    eventGuids_.add(value);
  }
  /**
   * <pre>
   * Array of event guids.
   * </pre>
   *
   * <code>repeated string event_guids = 1;</code>
   * @param values The eventGuids to add.
   */
  private void addAllEventGuids(
      Iterable<String> values) {
    ensureEventGuidsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, eventGuids_);
  }
  /**
   * <pre>
   * Array of event guids.
   * </pre>
   *
   * <code>repeated string event_guids = 1;</code>
   */
  private void clearEventGuids() {
    eventGuids_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <pre>
   * Array of event guids.
   * </pre>
   *
   * <code>repeated string event_guids = 1;</code>
   * @param value The bytes of the eventGuids to add.
   */
  private void addEventGuidsBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureEventGuidsIsMutable();
    eventGuids_.add(value.toStringUtf8());
  }

  public static final int EVENT_BATCH_GUIDS_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<String> eventBatchGuids_;
  /**
   * <pre>
   * Array of event batch guids.
   * </pre>
   *
   * <code>repeated string event_batch_guids = 2;</code>
   * @return A list containing the eventBatchGuids.
   */
  @Override
  public java.util.List<String> getEventBatchGuidsList() {
    return eventBatchGuids_;
  }
  /**
   * <pre>
   * Array of event batch guids.
   * </pre>
   *
   * <code>repeated string event_batch_guids = 2;</code>
   * @return The count of eventBatchGuids.
   */
  @Override
  public int getEventBatchGuidsCount() {
    return eventBatchGuids_.size();
  }
  /**
   * <pre>
   * Array of event batch guids.
   * </pre>
   *
   * <code>repeated string event_batch_guids = 2;</code>
   * @param index The index of the element to return.
   * @return The eventBatchGuids at the given index.
   */
  @Override
  public String getEventBatchGuids(int index) {
    return eventBatchGuids_.get(index);
  }
  /**
   * <pre>
   * Array of event batch guids.
   * </pre>
   *
   * <code>repeated string event_batch_guids = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the eventBatchGuids at the given index.
   */
  @Override
  public com.google.protobuf.ByteString
      getEventBatchGuidsBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        eventBatchGuids_.get(index));
  }
  private void ensureEventBatchGuidsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<String> tmp =
        eventBatchGuids_;  if (!tmp.isModifiable()) {
      eventBatchGuids_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <pre>
   * Array of event batch guids.
   * </pre>
   *
   * <code>repeated string event_batch_guids = 2;</code>
   * @param index The index to set the value at.
   * @param value The eventBatchGuids to set.
   */
  private void setEventBatchGuids(
      int index, String value) {
    Class<?> valueClass = value.getClass();
  ensureEventBatchGuidsIsMutable();
    eventBatchGuids_.set(index, value);
  }
  /**
   * <pre>
   * Array of event batch guids.
   * </pre>
   *
   * <code>repeated string event_batch_guids = 2;</code>
   * @param value The eventBatchGuids to add.
   */
  private void addEventBatchGuids(
      String value) {
    Class<?> valueClass = value.getClass();
  ensureEventBatchGuidsIsMutable();
    eventBatchGuids_.add(value);
  }
  /**
   * <pre>
   * Array of event batch guids.
   * </pre>
   *
   * <code>repeated string event_batch_guids = 2;</code>
   * @param values The eventBatchGuids to add.
   */
  private void addAllEventBatchGuids(
      Iterable<String> values) {
    ensureEventBatchGuidsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, eventBatchGuids_);
  }
  /**
   * <pre>
   * Array of event batch guids.
   * </pre>
   *
   * <code>repeated string event_batch_guids = 2;</code>
   */
  private void clearEventBatchGuids() {
    eventBatchGuids_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <pre>
   * Array of event batch guids.
   * </pre>
   *
   * <code>repeated string event_batch_guids = 2;</code>
   * @param value The bytes of the eventBatchGuids to add.
   */
  private void addEventBatchGuidsBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureEventBatchGuidsIsMutable();
    eventBatchGuids_.add(value.toStringUtf8());
  }

  public static HealthDetails parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static HealthDetails parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static HealthDetails parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static HealthDetails parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static HealthDetails parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static HealthDetails parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static HealthDetails parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static HealthDetails parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static HealthDetails parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static HealthDetails parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static HealthDetails parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static HealthDetails parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(HealthDetails prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code clickstream.health.proto.HealthDetails}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        HealthDetails, Builder> implements
      // @@protoc_insertion_point(builder_implements:clickstream.health.proto.HealthDetails)
      HealthDetailsOrBuilder {
    // Construct using clickstream.health.proto.HealthDetails.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Array of event guids.
     * </pre>
     *
     * <code>repeated string event_guids = 1;</code>
     * @return A list containing the eventGuids.
     */
    @Override
    public java.util.List<String>
        getEventGuidsList() {
      return java.util.Collections.unmodifiableList(
          instance.getEventGuidsList());
    }
    /**
     * <pre>
     * Array of event guids.
     * </pre>
     *
     * <code>repeated string event_guids = 1;</code>
     * @return The count of eventGuids.
     */
    @Override
    public int getEventGuidsCount() {
      return instance.getEventGuidsCount();
    }
    /**
     * <pre>
     * Array of event guids.
     * </pre>
     *
     * <code>repeated string event_guids = 1;</code>
     * @param index The index of the element to return.
     * @return The eventGuids at the given index.
     */
    @Override
    public String getEventGuids(int index) {
      return instance.getEventGuids(index);
    }
    /**
     * <pre>
     * Array of event guids.
     * </pre>
     *
     * <code>repeated string event_guids = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the eventGuids at the given index.
     */
    @Override
    public com.google.protobuf.ByteString
        getEventGuidsBytes(int index) {
      return instance.getEventGuidsBytes(index);
    }
    /**
     * <pre>
     * Array of event guids.
     * </pre>
     *
     * <code>repeated string event_guids = 1;</code>
     * @param index The index to set the value at.
     * @param value The eventGuids to set.
     * @return This builder for chaining.
     */
    public Builder setEventGuids(
        int index, String value) {
      copyOnWrite();
      instance.setEventGuids(index, value);
      return this;
    }
    /**
     * <pre>
     * Array of event guids.
     * </pre>
     *
     * <code>repeated string event_guids = 1;</code>
     * @param value The eventGuids to add.
     * @return This builder for chaining.
     */
    public Builder addEventGuids(
        String value) {
      copyOnWrite();
      instance.addEventGuids(value);
      return this;
    }
    /**
     * <pre>
     * Array of event guids.
     * </pre>
     *
     * <code>repeated string event_guids = 1;</code>
     * @param values The eventGuids to add.
     * @return This builder for chaining.
     */
    public Builder addAllEventGuids(
        Iterable<String> values) {
      copyOnWrite();
      instance.addAllEventGuids(values);
      return this;
    }
    /**
     * <pre>
     * Array of event guids.
     * </pre>
     *
     * <code>repeated string event_guids = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventGuids() {
      copyOnWrite();
      instance.clearEventGuids();
      return this;
    }
    /**
     * <pre>
     * Array of event guids.
     * </pre>
     *
     * <code>repeated string event_guids = 1;</code>
     * @param value The bytes of the eventGuids to add.
     * @return This builder for chaining.
     */
    public Builder addEventGuidsBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addEventGuidsBytes(value);
      return this;
    }

    /**
     * <pre>
     * Array of event batch guids.
     * </pre>
     *
     * <code>repeated string event_batch_guids = 2;</code>
     * @return A list containing the eventBatchGuids.
     */
    @Override
    public java.util.List<String>
        getEventBatchGuidsList() {
      return java.util.Collections.unmodifiableList(
          instance.getEventBatchGuidsList());
    }
    /**
     * <pre>
     * Array of event batch guids.
     * </pre>
     *
     * <code>repeated string event_batch_guids = 2;</code>
     * @return The count of eventBatchGuids.
     */
    @Override
    public int getEventBatchGuidsCount() {
      return instance.getEventBatchGuidsCount();
    }
    /**
     * <pre>
     * Array of event batch guids.
     * </pre>
     *
     * <code>repeated string event_batch_guids = 2;</code>
     * @param index The index of the element to return.
     * @return The eventBatchGuids at the given index.
     */
    @Override
    public String getEventBatchGuids(int index) {
      return instance.getEventBatchGuids(index);
    }
    /**
     * <pre>
     * Array of event batch guids.
     * </pre>
     *
     * <code>repeated string event_batch_guids = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the eventBatchGuids at the given index.
     */
    @Override
    public com.google.protobuf.ByteString
        getEventBatchGuidsBytes(int index) {
      return instance.getEventBatchGuidsBytes(index);
    }
    /**
     * <pre>
     * Array of event batch guids.
     * </pre>
     *
     * <code>repeated string event_batch_guids = 2;</code>
     * @param index The index to set the value at.
     * @param value The eventBatchGuids to set.
     * @return This builder for chaining.
     */
    public Builder setEventBatchGuids(
        int index, String value) {
      copyOnWrite();
      instance.setEventBatchGuids(index, value);
      return this;
    }
    /**
     * <pre>
     * Array of event batch guids.
     * </pre>
     *
     * <code>repeated string event_batch_guids = 2;</code>
     * @param value The eventBatchGuids to add.
     * @return This builder for chaining.
     */
    public Builder addEventBatchGuids(
        String value) {
      copyOnWrite();
      instance.addEventBatchGuids(value);
      return this;
    }
    /**
     * <pre>
     * Array of event batch guids.
     * </pre>
     *
     * <code>repeated string event_batch_guids = 2;</code>
     * @param values The eventBatchGuids to add.
     * @return This builder for chaining.
     */
    public Builder addAllEventBatchGuids(
        Iterable<String> values) {
      copyOnWrite();
      instance.addAllEventBatchGuids(values);
      return this;
    }
    /**
     * <pre>
     * Array of event batch guids.
     * </pre>
     *
     * <code>repeated string event_batch_guids = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventBatchGuids() {
      copyOnWrite();
      instance.clearEventBatchGuids();
      return this;
    }
    /**
     * <pre>
     * Array of event batch guids.
     * </pre>
     *
     * <code>repeated string event_batch_guids = 2;</code>
     * @param value The bytes of the eventBatchGuids to add.
     * @return This builder for chaining.
     */
    public Builder addEventBatchGuidsBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addEventBatchGuidsBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:clickstream.health.proto.HealthDetails)
  }
  @Override
  @SuppressWarnings({"unchecked", "fallthrough"})
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new HealthDetails();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          Object[] objects = new Object[] {
            "eventGuids_",
            "eventBatchGuids_",
          };
          String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0002\u0000\u0001\u021a\u0002\u021a" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<HealthDetails> parser = PARSER;
        if (parser == null) {
          synchronized (HealthDetails.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<HealthDetails>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:clickstream.health.proto.HealthDetails)
  private static final HealthDetails DEFAULT_INSTANCE;
  static {
    HealthDetails defaultInstance = new HealthDetails();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      HealthDetails.class, defaultInstance);
  }

  public static HealthDetails getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<HealthDetails> PARSER;

  public static com.google.protobuf.Parser<HealthDetails> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

