// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Health.proto

package clickstream.health.proto;

public interface HealthOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clickstream.health.proto.Health)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Name of the health event.
   * </pre>
   *
   * <code>string event_name = 1;</code>
   * @return The eventName.
   */
  String getEventName();
  /**
   * <pre>
   * Name of the health event.
   * </pre>
   *
   * <code>string event_name = 1;</code>
   * @return The bytes for eventName.
   */
  com.google.protobuf.ByteString
      getEventNameBytes();

  /**
   * <pre>
   * Health details, captured by the SDK when the mode is verbose.
   * </pre>
   *
   * <code>.clickstream.health.proto.HealthDetails healthDetails = 2;</code>
   * @return Whether the healthDetails field is set.
   */
  boolean hasHealthDetails();
  /**
   * <pre>
   * Health details, captured by the SDK when the mode is verbose.
   * </pre>
   *
   * <code>.clickstream.health.proto.HealthDetails healthDetails = 2;</code>
   * @return The healthDetails.
   */
  HealthDetails getHealthDetails();

  /**
   * <pre>
   * Number of events tracked.
   * </pre>
   *
   * <code>int64 number_of_events = 3;</code>
   * @return The numberOfEvents.
   */
  long getNumberOfEvents();

  /**
   * <pre>
   * Number of event batches tracked.
   * </pre>
   *
   * <code>int64 number_of_batches = 4;</code>
   * @return The numberOfBatches.
   */
  long getNumberOfBatches();

  /**
   * <pre>
   * Note: Auto-filled by the ClickStream SDK, need not be set by the products for every event! If set, will be overridden.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp event_timestamp = 101;</code>
   * @return Whether the eventTimestamp field is set.
   */
  boolean hasEventTimestamp();
  /**
   * <pre>
   * Note: Auto-filled by the ClickStream SDK, need not be set by the products for every event! If set, will be overridden.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp event_timestamp = 101;</code>
   * @return The eventTimestamp.
   */
  com.google.protobuf.Timestamp getEventTimestamp();

  /**
   * <code>.clickstream.health.proto.HealthMeta healthMeta = 103;</code>
   * @return Whether the healthMeta field is set.
   */
  boolean hasHealthMeta();
  /**
   * <code>.clickstream.health.proto.HealthMeta healthMeta = 103;</code>
   * @return The healthMeta.
   */
  HealthMeta getHealthMeta();

  /**
   * <pre>
   * Note: Auto-filled by the ClickStream SDK, need not be set by the products for every event! If set, will be overridden.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp device_timestamp = 104;</code>
   * @return Whether the deviceTimestamp field is set.
   */
  boolean hasDeviceTimestamp();
  /**
   * <pre>
   * Note: Auto-filled by the ClickStream SDK, need not be set by the products for every event! If set, will be overridden.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp device_timestamp = 104;</code>
   * @return The deviceTimestamp.
   */
  com.google.protobuf.Timestamp getDeviceTimestamp();
}
