// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HealthMeta.proto

package clickstream.health.proto;

/**
 * Protobuf type {@code clickstream.health.proto.HealthMeta}
 */
public  final class HealthMeta extends
    com.google.protobuf.GeneratedMessageLite<
        HealthMeta, HealthMeta.Builder> implements
    // @@protoc_insertion_point(message_implements:clickstream.health.proto.HealthMeta)
    HealthMetaOrBuilder {
  private HealthMeta() {
    eventGuid_ = "";
  }
  public interface AppOrBuilder extends
      // @@protoc_insertion_point(interface_extends:clickstream.health.proto.HealthMeta.App)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string version = 1;</code>
     * @return The version.
     */
    String getVersion();
    /**
     * <code>string version = 1;</code>
     * @return The bytes for version.
     */
    com.google.protobuf.ByteString
        getVersionBytes();
  }
  /**
   * Protobuf type {@code clickstream.health.proto.HealthMeta.App}
   */
  public  static final class App extends
      com.google.protobuf.GeneratedMessageLite<
          App, App.Builder> implements
      // @@protoc_insertion_point(message_implements:clickstream.health.proto.HealthMeta.App)
      AppOrBuilder {
    private App() {
      version_ = "";
    }
    public static final int VERSION_FIELD_NUMBER = 1;
    private String version_;
    /**
     * <code>string version = 1;</code>
     * @return The version.
     */
    @Override
    public String getVersion() {
      return version_;
    }
    /**
     * <code>string version = 1;</code>
     * @return The bytes for version.
     */
    @Override
    public com.google.protobuf.ByteString
        getVersionBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(version_);
    }
    /**
     * <code>string version = 1;</code>
     * @param value The version to set.
     */
    private void setVersion(
        String value) {
      Class<?> valueClass = value.getClass();
  
      version_ = value;
    }
    /**
     * <code>string version = 1;</code>
     */
    private void clearVersion() {
      
      version_ = getDefaultInstance().getVersion();
    }
    /**
     * <code>string version = 1;</code>
     * @param value The bytes for version to set.
     */
    private void setVersionBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      version_ = value.toStringUtf8();
      
    }

    public static App parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static App parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static App parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static App parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static App parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static App parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static App parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static App parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static App parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static App parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static App parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static App parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(App prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code clickstream.health.proto.HealthMeta.App}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          App, Builder> implements
        // @@protoc_insertion_point(builder_implements:clickstream.health.proto.HealthMeta.App)
        AppOrBuilder {
      // Construct using clickstream.health.proto.HealthMeta.App.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string version = 1;</code>
       * @return The version.
       */
      @Override
      public String getVersion() {
        return instance.getVersion();
      }
      /**
       * <code>string version = 1;</code>
       * @return The bytes for version.
       */
      @Override
      public com.google.protobuf.ByteString
          getVersionBytes() {
        return instance.getVersionBytes();
      }
      /**
       * <code>string version = 1;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(
          String value) {
        copyOnWrite();
        instance.setVersion(value);
        return this;
      }
      /**
       * <code>string version = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        copyOnWrite();
        instance.clearVersion();
        return this;
      }
      /**
       * <code>string version = 1;</code>
       * @param value The bytes for version to set.
       * @return This builder for chaining.
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setVersionBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:clickstream.health.proto.HealthMeta.App)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new App();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "version_",
            };
            String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<App> parser = PARSER;
          if (parser == null) {
            synchronized (App.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<App>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:clickstream.health.proto.HealthMeta.App)
    private static final App DEFAULT_INSTANCE;
    static {
      App defaultInstance = new App();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        App.class, defaultInstance);
    }

    public static App getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<App> PARSER;

    public static com.google.protobuf.Parser<App> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface CustomerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:clickstream.health.proto.HealthMeta.Customer)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string signed_up_country = 1;</code>
     * @return The signedUpCountry.
     */
    String getSignedUpCountry();
    /**
     * <code>string signed_up_country = 1;</code>
     * @return The bytes for signedUpCountry.
     */
    com.google.protobuf.ByteString
        getSignedUpCountryBytes();

    /**
     * <code>string current_country = 2;</code>
     * @return The currentCountry.
     */
    String getCurrentCountry();
    /**
     * <code>string current_country = 2;</code>
     * @return The bytes for currentCountry.
     */
    com.google.protobuf.ByteString
        getCurrentCountryBytes();

    /**
     * <code>int32 identity = 3;</code>
     * @return The identity.
     */
    int getIdentity();

    /**
     * <code>string email = 4;</code>
     * @return The email.
     */
    String getEmail();
    /**
     * <code>string email = 4;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();
  }
  /**
   * Protobuf type {@code clickstream.health.proto.HealthMeta.Customer}
   */
  public  static final class Customer extends
      com.google.protobuf.GeneratedMessageLite<
          Customer, Customer.Builder> implements
      // @@protoc_insertion_point(message_implements:clickstream.health.proto.HealthMeta.Customer)
      CustomerOrBuilder {
    private Customer() {
      signedUpCountry_ = "";
      currentCountry_ = "";
      email_ = "";
    }
    public static final int SIGNED_UP_COUNTRY_FIELD_NUMBER = 1;
    private String signedUpCountry_;
    /**
     * <code>string signed_up_country = 1;</code>
     * @return The signedUpCountry.
     */
    @Override
    public String getSignedUpCountry() {
      return signedUpCountry_;
    }
    /**
     * <code>string signed_up_country = 1;</code>
     * @return The bytes for signedUpCountry.
     */
    @Override
    public com.google.protobuf.ByteString
        getSignedUpCountryBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(signedUpCountry_);
    }
    /**
     * <code>string signed_up_country = 1;</code>
     * @param value The signedUpCountry to set.
     */
    private void setSignedUpCountry(
        String value) {
      Class<?> valueClass = value.getClass();
  
      signedUpCountry_ = value;
    }
    /**
     * <code>string signed_up_country = 1;</code>
     */
    private void clearSignedUpCountry() {
      
      signedUpCountry_ = getDefaultInstance().getSignedUpCountry();
    }
    /**
     * <code>string signed_up_country = 1;</code>
     * @param value The bytes for signedUpCountry to set.
     */
    private void setSignedUpCountryBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      signedUpCountry_ = value.toStringUtf8();
      
    }

    public static final int CURRENT_COUNTRY_FIELD_NUMBER = 2;
    private String currentCountry_;
    /**
     * <code>string current_country = 2;</code>
     * @return The currentCountry.
     */
    @Override
    public String getCurrentCountry() {
      return currentCountry_;
    }
    /**
     * <code>string current_country = 2;</code>
     * @return The bytes for currentCountry.
     */
    @Override
    public com.google.protobuf.ByteString
        getCurrentCountryBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(currentCountry_);
    }
    /**
     * <code>string current_country = 2;</code>
     * @param value The currentCountry to set.
     */
    private void setCurrentCountry(
        String value) {
      Class<?> valueClass = value.getClass();
  
      currentCountry_ = value;
    }
    /**
     * <code>string current_country = 2;</code>
     */
    private void clearCurrentCountry() {
      
      currentCountry_ = getDefaultInstance().getCurrentCountry();
    }
    /**
     * <code>string current_country = 2;</code>
     * @param value The bytes for currentCountry to set.
     */
    private void setCurrentCountryBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      currentCountry_ = value.toStringUtf8();
      
    }

    public static final int IDENTITY_FIELD_NUMBER = 3;
    private int identity_;
    /**
     * <code>int32 identity = 3;</code>
     * @return The identity.
     */
    @Override
    public int getIdentity() {
      return identity_;
    }
    /**
     * <code>int32 identity = 3;</code>
     * @param value The identity to set.
     */
    private void setIdentity(int value) {
      
      identity_ = value;
    }
    /**
     * <code>int32 identity = 3;</code>
     */
    private void clearIdentity() {
      
      identity_ = 0;
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    private String email_;
    /**
     * <code>string email = 4;</code>
     * @return The email.
     */
    @Override
    public String getEmail() {
      return email_;
    }
    /**
     * <code>string email = 4;</code>
     * @return The bytes for email.
     */
    @Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(email_);
    }
    /**
     * <code>string email = 4;</code>
     * @param value The email to set.
     */
    private void setEmail(
        String value) {
      Class<?> valueClass = value.getClass();
  
      email_ = value;
    }
    /**
     * <code>string email = 4;</code>
     */
    private void clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
    }
    /**
     * <code>string email = 4;</code>
     * @param value The bytes for email to set.
     */
    private void setEmailBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      email_ = value.toStringUtf8();
      
    }

    public static Customer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Customer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Customer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Customer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Customer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Customer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Customer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Customer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Customer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Customer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Customer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Customer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Customer prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code clickstream.health.proto.HealthMeta.Customer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Customer, Builder> implements
        // @@protoc_insertion_point(builder_implements:clickstream.health.proto.HealthMeta.Customer)
        CustomerOrBuilder {
      // Construct using clickstream.health.proto.HealthMeta.Customer.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string signed_up_country = 1;</code>
       * @return The signedUpCountry.
       */
      @Override
      public String getSignedUpCountry() {
        return instance.getSignedUpCountry();
      }
      /**
       * <code>string signed_up_country = 1;</code>
       * @return The bytes for signedUpCountry.
       */
      @Override
      public com.google.protobuf.ByteString
          getSignedUpCountryBytes() {
        return instance.getSignedUpCountryBytes();
      }
      /**
       * <code>string signed_up_country = 1;</code>
       * @param value The signedUpCountry to set.
       * @return This builder for chaining.
       */
      public Builder setSignedUpCountry(
          String value) {
        copyOnWrite();
        instance.setSignedUpCountry(value);
        return this;
      }
      /**
       * <code>string signed_up_country = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignedUpCountry() {
        copyOnWrite();
        instance.clearSignedUpCountry();
        return this;
      }
      /**
       * <code>string signed_up_country = 1;</code>
       * @param value The bytes for signedUpCountry to set.
       * @return This builder for chaining.
       */
      public Builder setSignedUpCountryBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSignedUpCountryBytes(value);
        return this;
      }

      /**
       * <code>string current_country = 2;</code>
       * @return The currentCountry.
       */
      @Override
      public String getCurrentCountry() {
        return instance.getCurrentCountry();
      }
      /**
       * <code>string current_country = 2;</code>
       * @return The bytes for currentCountry.
       */
      @Override
      public com.google.protobuf.ByteString
          getCurrentCountryBytes() {
        return instance.getCurrentCountryBytes();
      }
      /**
       * <code>string current_country = 2;</code>
       * @param value The currentCountry to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentCountry(
          String value) {
        copyOnWrite();
        instance.setCurrentCountry(value);
        return this;
      }
      /**
       * <code>string current_country = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentCountry() {
        copyOnWrite();
        instance.clearCurrentCountry();
        return this;
      }
      /**
       * <code>string current_country = 2;</code>
       * @param value The bytes for currentCountry to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentCountryBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCurrentCountryBytes(value);
        return this;
      }

      /**
       * <code>int32 identity = 3;</code>
       * @return The identity.
       */
      @Override
      public int getIdentity() {
        return instance.getIdentity();
      }
      /**
       * <code>int32 identity = 3;</code>
       * @param value The identity to set.
       * @return This builder for chaining.
       */
      public Builder setIdentity(int value) {
        copyOnWrite();
        instance.setIdentity(value);
        return this;
      }
      /**
       * <code>int32 identity = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdentity() {
        copyOnWrite();
        instance.clearIdentity();
        return this;
      }

      /**
       * <code>string email = 4;</code>
       * @return The email.
       */
      @Override
      public String getEmail() {
        return instance.getEmail();
      }
      /**
       * <code>string email = 4;</code>
       * @return The bytes for email.
       */
      @Override
      public com.google.protobuf.ByteString
          getEmailBytes() {
        return instance.getEmailBytes();
      }
      /**
       * <code>string email = 4;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          String value) {
        copyOnWrite();
        instance.setEmail(value);
        return this;
      }
      /**
       * <code>string email = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        copyOnWrite();
        instance.clearEmail();
        return this;
      }
      /**
       * <code>string email = 4;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmailBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:clickstream.health.proto.HealthMeta.Customer)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Customer();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "signedUpCountry_",
              "currentCountry_",
              "identity_",
              "email_",
            };
            String info =
                "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "\u0003\u0004\u0004\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Customer> parser = PARSER;
          if (parser == null) {
            synchronized (Customer.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Customer>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:clickstream.health.proto.HealthMeta.Customer)
    private static final Customer DEFAULT_INSTANCE;
    static {
      Customer defaultInstance = new Customer();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Customer.class, defaultInstance);
    }

    public static Customer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Customer> PARSER;

    public static com.google.protobuf.Parser<Customer> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface DeviceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:clickstream.health.proto.HealthMeta.Device)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string operating_system = 1;</code>
     * @return The operatingSystem.
     */
    String getOperatingSystem();
    /**
     * <code>string operating_system = 1;</code>
     * @return The bytes for operatingSystem.
     */
    com.google.protobuf.ByteString
        getOperatingSystemBytes();

    /**
     * <code>string operating_system_version = 2;</code>
     * @return The operatingSystemVersion.
     */
    String getOperatingSystemVersion();
    /**
     * <code>string operating_system_version = 2;</code>
     * @return The bytes for operatingSystemVersion.
     */
    com.google.protobuf.ByteString
        getOperatingSystemVersionBytes();

    /**
     * <code>string device_make = 3;</code>
     * @return The deviceMake.
     */
    String getDeviceMake();
    /**
     * <code>string device_make = 3;</code>
     * @return The bytes for deviceMake.
     */
    com.google.protobuf.ByteString
        getDeviceMakeBytes();

    /**
     * <code>string device_model = 4;</code>
     * @return The deviceModel.
     */
    String getDeviceModel();
    /**
     * <code>string device_model = 4;</code>
     * @return The bytes for deviceModel.
     */
    com.google.protobuf.ByteString
        getDeviceModelBytes();
  }
  /**
   * Protobuf type {@code clickstream.health.proto.HealthMeta.Device}
   */
  public  static final class Device extends
      com.google.protobuf.GeneratedMessageLite<
          Device, Device.Builder> implements
      // @@protoc_insertion_point(message_implements:clickstream.health.proto.HealthMeta.Device)
      DeviceOrBuilder {
    private Device() {
      operatingSystem_ = "";
      operatingSystemVersion_ = "";
      deviceMake_ = "";
      deviceModel_ = "";
    }
    public static final int OPERATING_SYSTEM_FIELD_NUMBER = 1;
    private String operatingSystem_;
    /**
     * <code>string operating_system = 1;</code>
     * @return The operatingSystem.
     */
    @Override
    public String getOperatingSystem() {
      return operatingSystem_;
    }
    /**
     * <code>string operating_system = 1;</code>
     * @return The bytes for operatingSystem.
     */
    @Override
    public com.google.protobuf.ByteString
        getOperatingSystemBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(operatingSystem_);
    }
    /**
     * <code>string operating_system = 1;</code>
     * @param value The operatingSystem to set.
     */
    private void setOperatingSystem(
        String value) {
      Class<?> valueClass = value.getClass();
  
      operatingSystem_ = value;
    }
    /**
     * <code>string operating_system = 1;</code>
     */
    private void clearOperatingSystem() {
      
      operatingSystem_ = getDefaultInstance().getOperatingSystem();
    }
    /**
     * <code>string operating_system = 1;</code>
     * @param value The bytes for operatingSystem to set.
     */
    private void setOperatingSystemBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      operatingSystem_ = value.toStringUtf8();
      
    }

    public static final int OPERATING_SYSTEM_VERSION_FIELD_NUMBER = 2;
    private String operatingSystemVersion_;
    /**
     * <code>string operating_system_version = 2;</code>
     * @return The operatingSystemVersion.
     */
    @Override
    public String getOperatingSystemVersion() {
      return operatingSystemVersion_;
    }
    /**
     * <code>string operating_system_version = 2;</code>
     * @return The bytes for operatingSystemVersion.
     */
    @Override
    public com.google.protobuf.ByteString
        getOperatingSystemVersionBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(operatingSystemVersion_);
    }
    /**
     * <code>string operating_system_version = 2;</code>
     * @param value The operatingSystemVersion to set.
     */
    private void setOperatingSystemVersion(
        String value) {
      Class<?> valueClass = value.getClass();
  
      operatingSystemVersion_ = value;
    }
    /**
     * <code>string operating_system_version = 2;</code>
     */
    private void clearOperatingSystemVersion() {
      
      operatingSystemVersion_ = getDefaultInstance().getOperatingSystemVersion();
    }
    /**
     * <code>string operating_system_version = 2;</code>
     * @param value The bytes for operatingSystemVersion to set.
     */
    private void setOperatingSystemVersionBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      operatingSystemVersion_ = value.toStringUtf8();
      
    }

    public static final int DEVICE_MAKE_FIELD_NUMBER = 3;
    private String deviceMake_;
    /**
     * <code>string device_make = 3;</code>
     * @return The deviceMake.
     */
    @Override
    public String getDeviceMake() {
      return deviceMake_;
    }
    /**
     * <code>string device_make = 3;</code>
     * @return The bytes for deviceMake.
     */
    @Override
    public com.google.protobuf.ByteString
        getDeviceMakeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(deviceMake_);
    }
    /**
     * <code>string device_make = 3;</code>
     * @param value The deviceMake to set.
     */
    private void setDeviceMake(
        String value) {
      Class<?> valueClass = value.getClass();
  
      deviceMake_ = value;
    }
    /**
     * <code>string device_make = 3;</code>
     */
    private void clearDeviceMake() {
      
      deviceMake_ = getDefaultInstance().getDeviceMake();
    }
    /**
     * <code>string device_make = 3;</code>
     * @param value The bytes for deviceMake to set.
     */
    private void setDeviceMakeBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      deviceMake_ = value.toStringUtf8();
      
    }

    public static final int DEVICE_MODEL_FIELD_NUMBER = 4;
    private String deviceModel_;
    /**
     * <code>string device_model = 4;</code>
     * @return The deviceModel.
     */
    @Override
    public String getDeviceModel() {
      return deviceModel_;
    }
    /**
     * <code>string device_model = 4;</code>
     * @return The bytes for deviceModel.
     */
    @Override
    public com.google.protobuf.ByteString
        getDeviceModelBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(deviceModel_);
    }
    /**
     * <code>string device_model = 4;</code>
     * @param value The deviceModel to set.
     */
    private void setDeviceModel(
        String value) {
      Class<?> valueClass = value.getClass();
  
      deviceModel_ = value;
    }
    /**
     * <code>string device_model = 4;</code>
     */
    private void clearDeviceModel() {
      
      deviceModel_ = getDefaultInstance().getDeviceModel();
    }
    /**
     * <code>string device_model = 4;</code>
     * @param value The bytes for deviceModel to set.
     */
    private void setDeviceModelBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      deviceModel_ = value.toStringUtf8();
      
    }

    public static Device parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Device parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Device parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Device parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Device parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Device parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Device parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Device parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Device parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Device parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Device parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Device parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Device prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code clickstream.health.proto.HealthMeta.Device}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Device, Builder> implements
        // @@protoc_insertion_point(builder_implements:clickstream.health.proto.HealthMeta.Device)
        DeviceOrBuilder {
      // Construct using clickstream.health.proto.HealthMeta.Device.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string operating_system = 1;</code>
       * @return The operatingSystem.
       */
      @Override
      public String getOperatingSystem() {
        return instance.getOperatingSystem();
      }
      /**
       * <code>string operating_system = 1;</code>
       * @return The bytes for operatingSystem.
       */
      @Override
      public com.google.protobuf.ByteString
          getOperatingSystemBytes() {
        return instance.getOperatingSystemBytes();
      }
      /**
       * <code>string operating_system = 1;</code>
       * @param value The operatingSystem to set.
       * @return This builder for chaining.
       */
      public Builder setOperatingSystem(
          String value) {
        copyOnWrite();
        instance.setOperatingSystem(value);
        return this;
      }
      /**
       * <code>string operating_system = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperatingSystem() {
        copyOnWrite();
        instance.clearOperatingSystem();
        return this;
      }
      /**
       * <code>string operating_system = 1;</code>
       * @param value The bytes for operatingSystem to set.
       * @return This builder for chaining.
       */
      public Builder setOperatingSystemBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setOperatingSystemBytes(value);
        return this;
      }

      /**
       * <code>string operating_system_version = 2;</code>
       * @return The operatingSystemVersion.
       */
      @Override
      public String getOperatingSystemVersion() {
        return instance.getOperatingSystemVersion();
      }
      /**
       * <code>string operating_system_version = 2;</code>
       * @return The bytes for operatingSystemVersion.
       */
      @Override
      public com.google.protobuf.ByteString
          getOperatingSystemVersionBytes() {
        return instance.getOperatingSystemVersionBytes();
      }
      /**
       * <code>string operating_system_version = 2;</code>
       * @param value The operatingSystemVersion to set.
       * @return This builder for chaining.
       */
      public Builder setOperatingSystemVersion(
          String value) {
        copyOnWrite();
        instance.setOperatingSystemVersion(value);
        return this;
      }
      /**
       * <code>string operating_system_version = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperatingSystemVersion() {
        copyOnWrite();
        instance.clearOperatingSystemVersion();
        return this;
      }
      /**
       * <code>string operating_system_version = 2;</code>
       * @param value The bytes for operatingSystemVersion to set.
       * @return This builder for chaining.
       */
      public Builder setOperatingSystemVersionBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setOperatingSystemVersionBytes(value);
        return this;
      }

      /**
       * <code>string device_make = 3;</code>
       * @return The deviceMake.
       */
      @Override
      public String getDeviceMake() {
        return instance.getDeviceMake();
      }
      /**
       * <code>string device_make = 3;</code>
       * @return The bytes for deviceMake.
       */
      @Override
      public com.google.protobuf.ByteString
          getDeviceMakeBytes() {
        return instance.getDeviceMakeBytes();
      }
      /**
       * <code>string device_make = 3;</code>
       * @param value The deviceMake to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceMake(
          String value) {
        copyOnWrite();
        instance.setDeviceMake(value);
        return this;
      }
      /**
       * <code>string device_make = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceMake() {
        copyOnWrite();
        instance.clearDeviceMake();
        return this;
      }
      /**
       * <code>string device_make = 3;</code>
       * @param value The bytes for deviceMake to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceMakeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDeviceMakeBytes(value);
        return this;
      }

      /**
       * <code>string device_model = 4;</code>
       * @return The deviceModel.
       */
      @Override
      public String getDeviceModel() {
        return instance.getDeviceModel();
      }
      /**
       * <code>string device_model = 4;</code>
       * @return The bytes for deviceModel.
       */
      @Override
      public com.google.protobuf.ByteString
          getDeviceModelBytes() {
        return instance.getDeviceModelBytes();
      }
      /**
       * <code>string device_model = 4;</code>
       * @param value The deviceModel to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceModel(
          String value) {
        copyOnWrite();
        instance.setDeviceModel(value);
        return this;
      }
      /**
       * <code>string device_model = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceModel() {
        copyOnWrite();
        instance.clearDeviceModel();
        return this;
      }
      /**
       * <code>string device_model = 4;</code>
       * @param value The bytes for deviceModel to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceModelBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDeviceModelBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:clickstream.health.proto.HealthMeta.Device)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Device();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "operatingSystem_",
              "operatingSystemVersion_",
              "deviceMake_",
              "deviceModel_",
            };
            String info =
                "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "\u0003\u0208\u0004\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Device> parser = PARSER;
          if (parser == null) {
            synchronized (Device.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Device>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:clickstream.health.proto.HealthMeta.Device)
    private static final Device DEFAULT_INSTANCE;
    static {
      Device defaultInstance = new Device();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Device.class, defaultInstance);
    }

    public static Device getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Device> PARSER;

    public static com.google.protobuf.Parser<Device> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface LocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:clickstream.health.proto.HealthMeta.Location)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>double latitude = 1;</code>
     * @return The latitude.
     */
    double getLatitude();

    /**
     * <code>double longitude = 2;</code>
     * @return The longitude.
     */
    double getLongitude();
  }
  /**
   * Protobuf type {@code clickstream.health.proto.HealthMeta.Location}
   */
  public  static final class Location extends
      com.google.protobuf.GeneratedMessageLite<
          Location, Location.Builder> implements
      // @@protoc_insertion_point(message_implements:clickstream.health.proto.HealthMeta.Location)
      LocationOrBuilder {
    private Location() {
    }
    public static final int LATITUDE_FIELD_NUMBER = 1;
    private double latitude_;
    /**
     * <code>double latitude = 1;</code>
     * @return The latitude.
     */
    @Override
    public double getLatitude() {
      return latitude_;
    }
    /**
     * <code>double latitude = 1;</code>
     * @param value The latitude to set.
     */
    private void setLatitude(double value) {
      
      latitude_ = value;
    }
    /**
     * <code>double latitude = 1;</code>
     */
    private void clearLatitude() {
      
      latitude_ = 0D;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private double longitude_;
    /**
     * <code>double longitude = 2;</code>
     * @return The longitude.
     */
    @Override
    public double getLongitude() {
      return longitude_;
    }
    /**
     * <code>double longitude = 2;</code>
     * @param value The longitude to set.
     */
    private void setLongitude(double value) {
      
      longitude_ = value;
    }
    /**
     * <code>double longitude = 2;</code>
     */
    private void clearLongitude() {
      
      longitude_ = 0D;
    }

    public static Location parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Location parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Location prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code clickstream.health.proto.HealthMeta.Location}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Location, Builder> implements
        // @@protoc_insertion_point(builder_implements:clickstream.health.proto.HealthMeta.Location)
        LocationOrBuilder {
      // Construct using clickstream.health.proto.HealthMeta.Location.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>double latitude = 1;</code>
       * @return The latitude.
       */
      @Override
      public double getLatitude() {
        return instance.getLatitude();
      }
      /**
       * <code>double latitude = 1;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(double value) {
        copyOnWrite();
        instance.setLatitude(value);
        return this;
      }
      /**
       * <code>double latitude = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        copyOnWrite();
        instance.clearLatitude();
        return this;
      }

      /**
       * <code>double longitude = 2;</code>
       * @return The longitude.
       */
      @Override
      public double getLongitude() {
        return instance.getLongitude();
      }
      /**
       * <code>double longitude = 2;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(double value) {
        copyOnWrite();
        instance.setLongitude(value);
        return this;
      }
      /**
       * <code>double longitude = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        copyOnWrite();
        instance.clearLongitude();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:clickstream.health.proto.HealthMeta.Location)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Location();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "latitude_",
              "longitude_",
            };
            String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0000\u0002\u0000" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Location> parser = PARSER;
          if (parser == null) {
            synchronized (Location.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Location>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:clickstream.health.proto.HealthMeta.Location)
    private static final Location DEFAULT_INSTANCE;
    static {
      Location defaultInstance = new Location();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Location.class, defaultInstance);
    }

    public static Location getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Location> PARSER;

    public static com.google.protobuf.Parser<Location> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SessionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:clickstream.health.proto.HealthMeta.Session)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string session_id = 1;</code>
     * @return The sessionId.
     */
    String getSessionId();
    /**
     * <code>string session_id = 1;</code>
     * @return The bytes for sessionId.
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();
  }
  /**
   * Protobuf type {@code clickstream.health.proto.HealthMeta.Session}
   */
  public  static final class Session extends
      com.google.protobuf.GeneratedMessageLite<
          Session, Session.Builder> implements
      // @@protoc_insertion_point(message_implements:clickstream.health.proto.HealthMeta.Session)
      SessionOrBuilder {
    private Session() {
      sessionId_ = "";
    }
    public static final int SESSION_ID_FIELD_NUMBER = 1;
    private String sessionId_;
    /**
     * <code>string session_id = 1;</code>
     * @return The sessionId.
     */
    @Override
    public String getSessionId() {
      return sessionId_;
    }
    /**
     * <code>string session_id = 1;</code>
     * @return The bytes for sessionId.
     */
    @Override
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(sessionId_);
    }
    /**
     * <code>string session_id = 1;</code>
     * @param value The sessionId to set.
     */
    private void setSessionId(
        String value) {
      Class<?> valueClass = value.getClass();
  
      sessionId_ = value;
    }
    /**
     * <code>string session_id = 1;</code>
     */
    private void clearSessionId() {
      
      sessionId_ = getDefaultInstance().getSessionId();
    }
    /**
     * <code>string session_id = 1;</code>
     * @param value The bytes for sessionId to set.
     */
    private void setSessionIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      sessionId_ = value.toStringUtf8();
      
    }

    public static Session parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Session parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Session parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Session parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Session parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Session parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Session parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Session parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Session parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Session parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Session parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Session parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Session prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code clickstream.health.proto.HealthMeta.Session}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Session, Builder> implements
        // @@protoc_insertion_point(builder_implements:clickstream.health.proto.HealthMeta.Session)
        SessionOrBuilder {
      // Construct using clickstream.health.proto.HealthMeta.Session.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string session_id = 1;</code>
       * @return The sessionId.
       */
      @Override
      public String getSessionId() {
        return instance.getSessionId();
      }
      /**
       * <code>string session_id = 1;</code>
       * @return The bytes for sessionId.
       */
      @Override
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        return instance.getSessionIdBytes();
      }
      /**
       * <code>string session_id = 1;</code>
       * @param value The sessionId to set.
       * @return This builder for chaining.
       */
      public Builder setSessionId(
          String value) {
        copyOnWrite();
        instance.setSessionId(value);
        return this;
      }
      /**
       * <code>string session_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSessionId() {
        copyOnWrite();
        instance.clearSessionId();
        return this;
      }
      /**
       * <code>string session_id = 1;</code>
       * @param value The bytes for sessionId to set.
       * @return This builder for chaining.
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSessionIdBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:clickstream.health.proto.HealthMeta.Session)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Session();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "sessionId_",
            };
            String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Session> parser = PARSER;
          if (parser == null) {
            synchronized (Session.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Session>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:clickstream.health.proto.HealthMeta.Session)
    private static final Session DEFAULT_INSTANCE;
    static {
      Session defaultInstance = new Session();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Session.class, defaultInstance);
    }

    public static Session getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Session> PARSER;

    public static com.google.protobuf.Parser<Session> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public static final int EVENT_GUID_FIELD_NUMBER = 1;
  private String eventGuid_;
  /**
   * <code>string event_guid = 1;</code>
   * @return The eventGuid.
   */
  @Override
  public String getEventGuid() {
    return eventGuid_;
  }
  /**
   * <code>string event_guid = 1;</code>
   * @return The bytes for eventGuid.
   */
  @Override
  public com.google.protobuf.ByteString
      getEventGuidBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(eventGuid_);
  }
  /**
   * <code>string event_guid = 1;</code>
   * @param value The eventGuid to set.
   */
  private void setEventGuid(
      String value) {
    Class<?> valueClass = value.getClass();
  
    eventGuid_ = value;
  }
  /**
   * <code>string event_guid = 1;</code>
   */
  private void clearEventGuid() {
    
    eventGuid_ = getDefaultInstance().getEventGuid();
  }
  /**
   * <code>string event_guid = 1;</code>
   * @param value The bytes for eventGuid to set.
   */
  private void setEventGuidBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    eventGuid_ = value.toStringUtf8();
    
  }

  public static final int LOCATION_FIELD_NUMBER = 4;
  private Location location_;
  /**
   * <code>.clickstream.health.proto.HealthMeta.Location location = 4;</code>
   */
  @Override
  public boolean hasLocation() {
    return location_ != null;
  }
  /**
   * <code>.clickstream.health.proto.HealthMeta.Location location = 4;</code>
   */
  @Override
  public Location getLocation() {
    return location_ == null ? Location.getDefaultInstance() : location_;
  }
  /**
   * <code>.clickstream.health.proto.HealthMeta.Location location = 4;</code>
   */
  private void setLocation(Location value) {
    value.getClass();
  location_ = value;
    
    }
  /**
   * <code>.clickstream.health.proto.HealthMeta.Location location = 4;</code>
   */
  @SuppressWarnings({"ReferenceEquality"})
  private void mergeLocation(Location value) {
    value.getClass();
  if (location_ != null &&
        location_ != Location.getDefaultInstance()) {
      location_ =
        Location.newBuilder(location_).mergeFrom(value).buildPartial();
    } else {
      location_ = value;
    }
    
  }
  /**
   * <code>.clickstream.health.proto.HealthMeta.Location location = 4;</code>
   */
  private void clearLocation() {  location_ = null;
    
  }

  public static final int CUSTOMER_FIELD_NUMBER = 5;
  private Customer customer_;
  /**
   * <code>.clickstream.health.proto.HealthMeta.Customer customer = 5;</code>
   */
  @Override
  public boolean hasCustomer() {
    return customer_ != null;
  }
  /**
   * <code>.clickstream.health.proto.HealthMeta.Customer customer = 5;</code>
   */
  @Override
  public Customer getCustomer() {
    return customer_ == null ? Customer.getDefaultInstance() : customer_;
  }
  /**
   * <code>.clickstream.health.proto.HealthMeta.Customer customer = 5;</code>
   */
  private void setCustomer(Customer value) {
    value.getClass();
  customer_ = value;
    
    }
  /**
   * <code>.clickstream.health.proto.HealthMeta.Customer customer = 5;</code>
   */
  @SuppressWarnings({"ReferenceEquality"})
  private void mergeCustomer(Customer value) {
    value.getClass();
  if (customer_ != null &&
        customer_ != Customer.getDefaultInstance()) {
      customer_ =
        Customer.newBuilder(customer_).mergeFrom(value).buildPartial();
    } else {
      customer_ = value;
    }
    
  }
  /**
   * <code>.clickstream.health.proto.HealthMeta.Customer customer = 5;</code>
   */
  private void clearCustomer() {  customer_ = null;
    
  }

  public static final int DEVICE_FIELD_NUMBER = 6;
  private Device device_;
  /**
   * <code>.clickstream.health.proto.HealthMeta.Device device = 6;</code>
   */
  @Override
  public boolean hasDevice() {
    return device_ != null;
  }
  /**
   * <code>.clickstream.health.proto.HealthMeta.Device device = 6;</code>
   */
  @Override
  public Device getDevice() {
    return device_ == null ? Device.getDefaultInstance() : device_;
  }
  /**
   * <code>.clickstream.health.proto.HealthMeta.Device device = 6;</code>
   */
  private void setDevice(Device value) {
    value.getClass();
  device_ = value;
    
    }
  /**
   * <code>.clickstream.health.proto.HealthMeta.Device device = 6;</code>
   */
  @SuppressWarnings({"ReferenceEquality"})
  private void mergeDevice(Device value) {
    value.getClass();
  if (device_ != null &&
        device_ != Device.getDefaultInstance()) {
      device_ =
        Device.newBuilder(device_).mergeFrom(value).buildPartial();
    } else {
      device_ = value;
    }
    
  }
  /**
   * <code>.clickstream.health.proto.HealthMeta.Device device = 6;</code>
   */
  private void clearDevice() {  device_ = null;
    
  }

  public static final int SESSION_FIELD_NUMBER = 7;
  private Session session_;
  /**
   * <code>.clickstream.health.proto.HealthMeta.Session session = 7;</code>
   */
  @Override
  public boolean hasSession() {
    return session_ != null;
  }
  /**
   * <code>.clickstream.health.proto.HealthMeta.Session session = 7;</code>
   */
  @Override
  public Session getSession() {
    return session_ == null ? Session.getDefaultInstance() : session_;
  }
  /**
   * <code>.clickstream.health.proto.HealthMeta.Session session = 7;</code>
   */
  private void setSession(Session value) {
    value.getClass();
  session_ = value;
    
    }
  /**
   * <code>.clickstream.health.proto.HealthMeta.Session session = 7;</code>
   */
  @SuppressWarnings({"ReferenceEquality"})
  private void mergeSession(Session value) {
    value.getClass();
  if (session_ != null &&
        session_ != Session.getDefaultInstance()) {
      session_ =
        Session.newBuilder(session_).mergeFrom(value).buildPartial();
    } else {
      session_ = value;
    }
    
  }
  /**
   * <code>.clickstream.health.proto.HealthMeta.Session session = 7;</code>
   */
  private void clearSession() {  session_ = null;
    
  }

  public static final int APP_FIELD_NUMBER = 8;
  private App app_;
  /**
   * <code>.clickstream.health.proto.HealthMeta.App app = 8;</code>
   */
  @Override
  public boolean hasApp() {
    return app_ != null;
  }
  /**
   * <code>.clickstream.health.proto.HealthMeta.App app = 8;</code>
   */
  @Override
  public App getApp() {
    return app_ == null ? App.getDefaultInstance() : app_;
  }
  /**
   * <code>.clickstream.health.proto.HealthMeta.App app = 8;</code>
   */
  private void setApp(App value) {
    value.getClass();
  app_ = value;
    
    }
  /**
   * <code>.clickstream.health.proto.HealthMeta.App app = 8;</code>
   */
  @SuppressWarnings({"ReferenceEquality"})
  private void mergeApp(App value) {
    value.getClass();
  if (app_ != null &&
        app_ != App.getDefaultInstance()) {
      app_ =
        App.newBuilder(app_).mergeFrom(value).buildPartial();
    } else {
      app_ = value;
    }
    
  }
  /**
   * <code>.clickstream.health.proto.HealthMeta.App app = 8;</code>
   */
  private void clearApp() {  app_ = null;
    
  }

  public static HealthMeta parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static HealthMeta parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static HealthMeta parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static HealthMeta parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static HealthMeta parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static HealthMeta parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static HealthMeta parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static HealthMeta parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static HealthMeta parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static HealthMeta parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static HealthMeta parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static HealthMeta parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(HealthMeta prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code clickstream.health.proto.HealthMeta}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        HealthMeta, Builder> implements
      // @@protoc_insertion_point(builder_implements:clickstream.health.proto.HealthMeta)
      HealthMetaOrBuilder {
    // Construct using clickstream.health.proto.HealthMeta.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string event_guid = 1;</code>
     * @return The eventGuid.
     */
    @Override
    public String getEventGuid() {
      return instance.getEventGuid();
    }
    /**
     * <code>string event_guid = 1;</code>
     * @return The bytes for eventGuid.
     */
    @Override
    public com.google.protobuf.ByteString
        getEventGuidBytes() {
      return instance.getEventGuidBytes();
    }
    /**
     * <code>string event_guid = 1;</code>
     * @param value The eventGuid to set.
     * @return This builder for chaining.
     */
    public Builder setEventGuid(
        String value) {
      copyOnWrite();
      instance.setEventGuid(value);
      return this;
    }
    /**
     * <code>string event_guid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventGuid() {
      copyOnWrite();
      instance.clearEventGuid();
      return this;
    }
    /**
     * <code>string event_guid = 1;</code>
     * @param value The bytes for eventGuid to set.
     * @return This builder for chaining.
     */
    public Builder setEventGuidBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setEventGuidBytes(value);
      return this;
    }

    /**
     * <code>.clickstream.health.proto.HealthMeta.Location location = 4;</code>
     */
    @Override
    public boolean hasLocation() {
      return instance.hasLocation();
    }
    /**
     * <code>.clickstream.health.proto.HealthMeta.Location location = 4;</code>
     */
    @Override
    public Location getLocation() {
      return instance.getLocation();
    }
    /**
     * <code>.clickstream.health.proto.HealthMeta.Location location = 4;</code>
     */
    public Builder setLocation(Location value) {
      copyOnWrite();
      instance.setLocation(value);
      return this;
      }
    /**
     * <code>.clickstream.health.proto.HealthMeta.Location location = 4;</code>
     */
    public Builder setLocation(
        Location.Builder builderForValue) {
      copyOnWrite();
      instance.setLocation(builderForValue.build());
      return this;
    }
    /**
     * <code>.clickstream.health.proto.HealthMeta.Location location = 4;</code>
     */
    public Builder mergeLocation(Location value) {
      copyOnWrite();
      instance.mergeLocation(value);
      return this;
    }
    /**
     * <code>.clickstream.health.proto.HealthMeta.Location location = 4;</code>
     */
    public Builder clearLocation() {  copyOnWrite();
      instance.clearLocation();
      return this;
    }

    /**
     * <code>.clickstream.health.proto.HealthMeta.Customer customer = 5;</code>
     */
    @Override
    public boolean hasCustomer() {
      return instance.hasCustomer();
    }
    /**
     * <code>.clickstream.health.proto.HealthMeta.Customer customer = 5;</code>
     */
    @Override
    public Customer getCustomer() {
      return instance.getCustomer();
    }
    /**
     * <code>.clickstream.health.proto.HealthMeta.Customer customer = 5;</code>
     */
    public Builder setCustomer(Customer value) {
      copyOnWrite();
      instance.setCustomer(value);
      return this;
      }
    /**
     * <code>.clickstream.health.proto.HealthMeta.Customer customer = 5;</code>
     */
    public Builder setCustomer(
        Customer.Builder builderForValue) {
      copyOnWrite();
      instance.setCustomer(builderForValue.build());
      return this;
    }
    /**
     * <code>.clickstream.health.proto.HealthMeta.Customer customer = 5;</code>
     */
    public Builder mergeCustomer(Customer value) {
      copyOnWrite();
      instance.mergeCustomer(value);
      return this;
    }
    /**
     * <code>.clickstream.health.proto.HealthMeta.Customer customer = 5;</code>
     */
    public Builder clearCustomer() {  copyOnWrite();
      instance.clearCustomer();
      return this;
    }

    /**
     * <code>.clickstream.health.proto.HealthMeta.Device device = 6;</code>
     */
    @Override
    public boolean hasDevice() {
      return instance.hasDevice();
    }
    /**
     * <code>.clickstream.health.proto.HealthMeta.Device device = 6;</code>
     */
    @Override
    public Device getDevice() {
      return instance.getDevice();
    }
    /**
     * <code>.clickstream.health.proto.HealthMeta.Device device = 6;</code>
     */
    public Builder setDevice(Device value) {
      copyOnWrite();
      instance.setDevice(value);
      return this;
      }
    /**
     * <code>.clickstream.health.proto.HealthMeta.Device device = 6;</code>
     */
    public Builder setDevice(
        Device.Builder builderForValue) {
      copyOnWrite();
      instance.setDevice(builderForValue.build());
      return this;
    }
    /**
     * <code>.clickstream.health.proto.HealthMeta.Device device = 6;</code>
     */
    public Builder mergeDevice(Device value) {
      copyOnWrite();
      instance.mergeDevice(value);
      return this;
    }
    /**
     * <code>.clickstream.health.proto.HealthMeta.Device device = 6;</code>
     */
    public Builder clearDevice() {  copyOnWrite();
      instance.clearDevice();
      return this;
    }

    /**
     * <code>.clickstream.health.proto.HealthMeta.Session session = 7;</code>
     */
    @Override
    public boolean hasSession() {
      return instance.hasSession();
    }
    /**
     * <code>.clickstream.health.proto.HealthMeta.Session session = 7;</code>
     */
    @Override
    public Session getSession() {
      return instance.getSession();
    }
    /**
     * <code>.clickstream.health.proto.HealthMeta.Session session = 7;</code>
     */
    public Builder setSession(Session value) {
      copyOnWrite();
      instance.setSession(value);
      return this;
      }
    /**
     * <code>.clickstream.health.proto.HealthMeta.Session session = 7;</code>
     */
    public Builder setSession(
        Session.Builder builderForValue) {
      copyOnWrite();
      instance.setSession(builderForValue.build());
      return this;
    }
    /**
     * <code>.clickstream.health.proto.HealthMeta.Session session = 7;</code>
     */
    public Builder mergeSession(Session value) {
      copyOnWrite();
      instance.mergeSession(value);
      return this;
    }
    /**
     * <code>.clickstream.health.proto.HealthMeta.Session session = 7;</code>
     */
    public Builder clearSession() {  copyOnWrite();
      instance.clearSession();
      return this;
    }

    /**
     * <code>.clickstream.health.proto.HealthMeta.App app = 8;</code>
     */
    @Override
    public boolean hasApp() {
      return instance.hasApp();
    }
    /**
     * <code>.clickstream.health.proto.HealthMeta.App app = 8;</code>
     */
    @Override
    public App getApp() {
      return instance.getApp();
    }
    /**
     * <code>.clickstream.health.proto.HealthMeta.App app = 8;</code>
     */
    public Builder setApp(App value) {
      copyOnWrite();
      instance.setApp(value);
      return this;
      }
    /**
     * <code>.clickstream.health.proto.HealthMeta.App app = 8;</code>
     */
    public Builder setApp(
        App.Builder builderForValue) {
      copyOnWrite();
      instance.setApp(builderForValue.build());
      return this;
    }
    /**
     * <code>.clickstream.health.proto.HealthMeta.App app = 8;</code>
     */
    public Builder mergeApp(App value) {
      copyOnWrite();
      instance.mergeApp(value);
      return this;
    }
    /**
     * <code>.clickstream.health.proto.HealthMeta.App app = 8;</code>
     */
    public Builder clearApp() {  copyOnWrite();
      instance.clearApp();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:clickstream.health.proto.HealthMeta)
  }
  @Override
  @SuppressWarnings({"unchecked", "fallthrough"})
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new HealthMeta();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          Object[] objects = new Object[] {
            "eventGuid_",
            "location_",
            "customer_",
            "device_",
            "session_",
            "app_",
          };
          String info =
              "\u0000\u0006\u0000\u0000\u0001\b\u0006\u0000\u0000\u0000\u0001\u0208\u0004\t\u0005" +
              "\t\u0006\t\u0007\t\b\t";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<HealthMeta> parser = PARSER;
        if (parser == null) {
          synchronized (HealthMeta.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<HealthMeta>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:clickstream.health.proto.HealthMeta)
  private static final HealthMeta DEFAULT_INSTANCE;
  static {
    HealthMeta defaultInstance = new HealthMeta();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      HealthMeta.class, defaultInstance);
  }

  public static HealthMeta getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<HealthMeta> PARSER;

  public static com.google.protobuf.Parser<HealthMeta> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

