// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Health.proto

package clickstream.health.proto;

public interface HealthDetailsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clickstream.health.proto.HealthDetails)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Array of event guids.
   * </pre>
   *
   * <code>repeated string event_guids = 1;</code>
   * @return A list containing the eventGuids.
   */
  java.util.List<String>
      getEventGuidsList();
  /**
   * <pre>
   * Array of event guids.
   * </pre>
   *
   * <code>repeated string event_guids = 1;</code>
   * @return The count of eventGuids.
   */
  int getEventGuidsCount();
  /**
   * <pre>
   * Array of event guids.
   * </pre>
   *
   * <code>repeated string event_guids = 1;</code>
   * @param index The index of the element to return.
   * @return The eventGuids at the given index.
   */
  String getEventGuids(int index);
  /**
   * <pre>
   * Array of event guids.
   * </pre>
   *
   * <code>repeated string event_guids = 1;</code>
   * @param index The index of the element to return.
   * @return The eventGuids at the given index.
   */
  com.google.protobuf.ByteString
      getEventGuidsBytes(int index);

  /**
   * <pre>
   * Array of event batch guids.
   * </pre>
   *
   * <code>repeated string event_batch_guids = 2;</code>
   * @return A list containing the eventBatchGuids.
   */
  java.util.List<String>
      getEventBatchGuidsList();
  /**
   * <pre>
   * Array of event batch guids.
   * </pre>
   *
   * <code>repeated string event_batch_guids = 2;</code>
   * @return The count of eventBatchGuids.
   */
  int getEventBatchGuidsCount();
  /**
   * <pre>
   * Array of event batch guids.
   * </pre>
   *
   * <code>repeated string event_batch_guids = 2;</code>
   * @param index The index of the element to return.
   * @return The eventBatchGuids at the given index.
   */
  String getEventBatchGuids(int index);
  /**
   * <pre>
   * Array of event batch guids.
   * </pre>
   *
   * <code>repeated string event_batch_guids = 2;</code>
   * @param index The index of the element to return.
   * @return The eventBatchGuids at the given index.
   */
  com.google.protobuf.ByteString
      getEventBatchGuidsBytes(int index);
}
