// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HealthMeta.proto

package clickstream.health.proto;

public final class HealthMetaProto {
  private HealthMetaProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
