name: Publish

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Push events to any matching semantic tag. For example, 1.10.1 or 2.0.0.
        # For more details, see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
        # and https://docs.npmjs.com/about-semantic-versioning

jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Release build
        run: ./gradlew :clickstream:assembleRelease
          :clickstream-api:assembleRelease
          :clickstream-logger:assembleRelease
          :clickstream-lifecycle:assembleRelease
          :clickstream-util:assembleRelease
          :clickstream-health-metrics:assembleRelease
          :clickstream-health-metrics-noop:assembleRelease
          :clickstream-health-metrics-api:assembleRelease
          :clickstream-event-interceptor:assemble
          :clickstream-event-visualiser:assembleRelease
          :clickstream-event-visualiser-noop:assembleRelease
          :clickstream-event-visualiser-ui:assembleRelease
      - name: Publish to MavenCentral
        run: ./gradlew :clickstream:publishReleasePublicationToSonatypeRepository
          :clickstream-api:publishReleasePublicationToSonatypeRepository
          :clickstream-logger:publishReleasePublicationToSonatypeRepository
          :clickstream-lifecycle:publishReleasePublicationToSonatypeRepository
          :clickstream-util:publishReleasePublicationToSonatypeRepository
          :clickstream-health-metrics:publishReleasePublicationToSonatypeRepository
          :clickstream-health-metrics-noop:publishReleasePublicationToSonatypeRepository
          :clickstream-health-metrics-api:publishReleasePublicationToSonatypeRepository
          :clickstream-event-interceptor:publishReleasePublicationToSonatypeRepository
          :clickstream-event-visualiser:publishReleasePublicationToSonatypeRepository
          :clickstream-event-visualiser-noop:publishReleasePublicationToSonatypeRepository
          :clickstream-event-visualiser-ui:publishReleasePublicationToSonatypeRepository
          :clickstream-event-visualiser-ui-noop:publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
